SigortaMusTakipProjesi/Models/Entity/Musteri.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigortaMusTakipProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.MusteriGorusme = new HashSet<MusteriGorusme>();
        }
    
        public int Id { get; set; }
        public string MusAdı { get; set; }
        public string MusSoyad { get; set; }
        public string Isyeri { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
        public Nullable<System.DateTime> KayıtTarihi { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriGorusme> MusteriGorusme { get; set; }
    }
}

SigortaMusTakipProjesi/Controllers/MusteriController.cs
using SigortaMusTakipProjesi.BusinessProcess;
using SigortaMusTakipProjesi.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SigortaMusTakipProjesi.Controllers
{
    public class MusteriController : Controller
    {

       MusteriManager musteriManager = new MusteriManager();
        MusteriGorusmeManager MusteriGorusmeManager = new MusteriGorusmeManager();
        // GET: Musteri
        public ActionResult Index()
        {
            var list = musteriManager.List();
            return View(list);
        }

        [HttpGet]
        public ActionResult NewMusteri() {

            return View();
        }

        [HttpPost]
        public ActionResult NewMusteri(Musteri m)
        {

            musteriManager.Save(m);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id) {

            musteriManager.Delete(id);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(Musteri m) {

            musteriManager.Edit(m);
            return RedirectToAction("Index");
        }

        public ActionResult FindMusteri(int id) {


            return View(musteriManager.FindById(id));
        }

        public ActionResult MusteriDetay(int id) {

            List<MusteriGorusme> musteriGorusmelist = MusteriGorusmeManager.List().Where(m => m.MusId == id).ToList();
            ViewBag.MusteriBilgileri = musteriManager.FindById(id).MusAdı + " " + musteriManager.FindById(id).MusSoyad;
            ViewBag.MusteriId = id;
            
            return View(musteriGorusmelist);
        }
    }
}

SigortaMusTakipProjesi/Views/Musteri/FindMusteri.cshtml
@model SigortaMusTakipProjesi.Models.Entity.Musteri
@{
    ViewBag.Title = "FindMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}



@using (Html.BeginForm("Edit", "Musteri", FormMethod.Post))
{

    <div class="form-group">
        <label>Musteri Id</label>
        @Html.TextBoxFor(m => m.Id, new { @class = "form-control" })

        <br />
        <label>Musteri Adı</label>
        @Html.TextBoxFor(m => m.MusAdı, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MusAdı, "", new { @style = "color:red" })

        <label>Musteri SoyAdı</label>
        @Html.TextBoxFor(m => m.MusSoyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MusSoyad, "", new { @style = "color:red" })

        <label>Musteri İşyeri</label>
        @Html.TextBoxFor(m => m.Isyeri, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Isyeri, "", new { @style = "color:red" })

        <label>Musteri Adres</label>
        @Html.TextBoxFor(m => m.Adres, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Adres, "", new { @style = "color:red" })

        <label>Musteri Telefon</label>
        @Html.TextBoxFor(m => m.Tel, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Tel, "", new { @style = "color:red" })

        <label>Kayıt Tarihi</label>
        @Html.EditorFor(m => m.KayıtTarihi,
         new
              {
                  htmlAttributes = new

         {
             @readonly = "true",
             Value = Model.KayıtTarihi,
             @class = "form-control datepicker"
         }
         })

        @Html.ValidationMessageFor(m => m.KayıtTarihi, "", new { @style = "color:red" })

        @if (Model.IsActive == false)
        {
            <br />
            <label>Musteri Aktif</label>


            <div class="form-control">
                Evet
                @Html.RadioButtonFor(m => m.IsActive, true)
                Hayır
                @Html.RadioButtonFor(m => m.IsActive, false)
            </div>

        }

    </div>

    <div>

        <button id="musguncelle" class="btn btn-warning" onclick="javascript: return guncelle();">Guncelle</button>
    </div>

}
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />


<script type="text/javascript">

    $(document).ready(function () {

        $(".datepicker").datepicker({


            changeMonth :true,
            changeYear: true,
            dateFormat :"yy-mm-dd"
            
        });
    });

    function guncelle() {

        var ok = confirm("Guncellemek istiyormusunuz?");
        if (ok == true) {
            return true;
        }
        return false;
    }

</script>

SigortaMusTakipProjesi/Views/Musteri/Index.cshtml
@using SigortaMusTakipProjesi.Models.Entity

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table id="tbl1" class="table table-bordered">

    <thead>

        <tr>
            <th>MüşteriId</th>
            <th>MüşteriAdı</th>
            <th>MüşteriSoyadı</th>
            <th>İşyeri</th>
            <th>Adres</th>
            <th>Telefon</th>
            <th>Kayıt Tarihi</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Detay</th>

        </tr>
    </thead>

    <tbody>
        @foreach (var must in Model)
        {
        <tr>
            @if (must.IsActive == false)
            {
                <td style="background-color:lightcoral">@must.Id</td>
            }
            else
            {
                <td>@must.Id</td>
            }
            <td>@must.MusAdı</td>
            <td>@must.MusSoyad</td>
            <td>@must.Isyeri</td>
            <td>@must.Adres</td>
            <td>@must.Tel</td>
            <td>@must.KayıtTarihi.ToString("dd-MM-yyyy")</td>
            <td><a href="/Musteri/DELETE/@must.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Musteri/FINDMUSTERI/@must.Id" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Musteri/MUSTERIDETAY/@must.Id" class="btn btn-success">Detay</a></td>
        </tr>
        }



    </tbody>

</table>

<a href="/Musteri/NewMusteri" class="btn btn-primary">YENİ MUSTERİ EKLE</a>


<link href="~/Content/DataTables/css/dataTables.bootstrap4.css" rel="stylesheet" />
<script type="text/javascript" src="https://cdn.datatables.net/v/bs-3.3.7/jq-2.2.4/jszip-3.1.3/pdfmake-0.1.27/dt-1.10.15/b-1.3.1/b-colvis-1.3.1/b-flash-1.3.1/b-html5-1.3.1/b-print-1.3.1/r-2.1.1/sc-1.4.2/se-1.2.2/datatables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#tbl1').DataTable({
            language: {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
            }
        });
    });

</script>

SigortaMusTakipProjesi/Views/Musteri/MusteriDetay.cshtml
@{
    ViewBag.Title = "MusteriDetay";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h4>
    Müşteri :  @ViewBag.MusteriBilgileri
</h4>

<table id="tbl1" class="table table-bordered">

    <thead>

        <tr>
            <th>Görüşme Id</th>
            <th>Görüşme Konusu</th>
            <th>Görüşme Tarihi </th>
            <th>Sil</th>
            <th>Güncelle</th>


        </tr>
    </thead>

    <tbody>
        @foreach (var mustGorustme in Model)
        {
        <tr>
            @if (mustGorustme.IsActive == false)
            {
                <td style="background-color:lightcoral">@mustGorustme.Id</td>
            }
            else
            {
                <td>@mustGorustme.Id</td>
            }
            <td>@mustGorustme.GorusmeKonusu</td>
            <td>@mustGorustme.GorusmeTarihi.ToString("dd-MM-yyyy")</td>

            <td><a href="/MusteriGorusme/DELETE/@mustGorustme.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/MusteriGorusme/FindMusteriGorusme/@mustGorustme.Id" class="btn btn-success">Güncelle</a></td>
        </tr>
        }



    </tbody>
    <a href="/MusteriGorusme/NewMusteriGorusme/@ViewBag.MusteriId" class="btn btn-primary">YENİ GORUSME EKLE</a>
</table>

@*<a href="/MusteriGorusme/NewMusteriGorusme/@ViewBag.MusteriId" class="btn btn-primary">YENİ GORUSME EKLE</a>*@

SigortaMusTakipProjesi/Views/Musteri/NewMusteri.cshtml
@model SigortaMusTakipProjesi.Models.Entity.Musteri
@{
    ViewBag.Title = "NewMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">

    <div>

        <label>Musteri Adı</label>

        @Html.TextBoxFor(m => m.MusAdı, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MusAdı, "", new { @style = "color:red" })

        <label>Musteri Soyadı</label>

        @Html.TextBoxFor(m => m.MusSoyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.MusSoyad, "", new { @style = "color:red" })

        <label>Musteri İşyeri</label>

        @Html.TextBoxFor(m => m.Isyeri, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Isyeri, "", new { @style = "color:red" })


        <label>Adres</label>

        @Html.TextBoxFor(m => m.Adres, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Adres, "", new { @style = "color:red" })


        <label>Telefon</label>

        @Html.TextBoxFor(m => m.Tel, new { @class = "form-control", type = "phone" })
        @Html.ValidationMessageFor(m => m.Tel, "", new { @style = "color:red" })


    </div>
    <div style="margin-top:15px">

        <button id="musteriEkle" class="btn btn-info">Musteri Ekle</button>
    </div>


</form>