SigortaMusTakipProjesi/Models/Entity/MusteriGorusme.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigortaMusTakipProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriGorusme
    {
        public int Id { get; set; }
        public Nullable<int> MusId { get; set; }
        public Nullable<System.DateTime> GorusmeTarihi { get; set; }
        public string GorusmeKonusu { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}

SigortaMusTakipProjesi/Controllers/MusteriGorusmeController.cs
using SigortaMusTakipProjesi.BusinessProcess;
using SigortaMusTakipProjesi.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SigortaMusTakipProjesi.Controllers
{
    public class MusteriGorusmeController : Controller
    {

        MusteriGorusmeManager musteriGorusmeManager = new MusteriGorusmeManager();
        // GET: MusteriGorusme
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult NewMusteriGorusme(int id)
        {

            ViewBag.musId = id;
            return View();
        }

        [HttpPost]
        public ActionResult NewMusteriGorusme(MusteriGorusme mg)
        {

            musteriGorusmeManager.Save(mg);

            //return View("~/Views/Musteri/index.cshtml");
            return RedirectToAction("Index", "Musteri");
        }

        public ActionResult Delete(int id)
        {

            musteriGorusmeManager.Delete(id);

            return RedirectToAction("Index", "Musteri");
        }

        public ActionResult Edit(MusteriGorusme mg)
        {

            musteriGorusmeManager.Edit(mg);
            return RedirectToAction("Index", "Musteri");
        }

        public ActionResult FindMusteriGorusme(int id)
        {


            return View(musteriGorusmeManager.FindById(id));
        }
    }
}

SigortaMusTakipProjesi/Views/MusteriGorusme/FindMusteriGorusme.cshtml
@model SigortaMusTakipProjesi.Models.Entity.MusteriGorusme

@{
    ViewBag.Title = "FindMusteriGorusme";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Edit", "MusteriGorusme", FormMethod.Post))
{

<div class="form-group">
    <label>Gorusme Id</label>
    @Html.TextBoxFor(m => m.Id, new { @class = "form-control" })

    <br />
    <label>Musteri Id</label>
    @Html.TextBoxFor(m => m.MusId, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.MusId, "", new { @style = "color:red" })

    <br />
    <label>Gorusme Konusu</label>
    @Html.TextBoxFor(m => m.GorusmeKonusu, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.GorusmeKonusu, "", new { @style = "color:red" })



    <label>Gorusme Tarihi</label>
    @Html.EditorFor(m => m.GorusmeTarihi,
     new
          {
              htmlAttributes = new

     {
         @readonly = "true",
         Value = Model.GorusmeTarihi,
         @class = "form-control datepicker"
     }
     })

    @Html.ValidationMessageFor(m => m.GorusmeTarihi, "", new { @style = "color:red" })

    @if (Model.IsActive == false)
    {
        <br />
        <label>Gorusme Aktif</label>


        <div class="form-control">
            Evet
            @Html.RadioButtonFor(m => m.IsActive, true)
            Hayır
            @Html.RadioButtonFor(m => m.IsActive, false)
        </div>

    }

</div>

    <div>

        <button id="musgorusmeguncelle" class="btn btn-warning" onclick="javascript: return guncelle();">Guncelle</button>
    </div>

}
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />


<script type="text/javascript">

    $(document).ready(function () {

        $(".datepicker").datepicker({


            changeMonth: true,
            changeYear: true,
            dateFormat: "yy-mm-dd"

        });
    });

    function guncelle() {

        var ok = confirm("Guncellemek istiyormusunuz?");
        if (ok == true) {
            return true;
        }
        return false;
    }

</script>

SigortaMusTakipProjesi/Views/MusteriGorusme/NewMusteriGorusme.cshtml
@model SigortaMusTakipProjesi.Models.Entity.MusteriGorusme
@{
    ViewBag.Title = "NewMusteriGorusme";
    Layout = "~/Views/Shared/_MainLayout.cshtml";


}
<form class="form-group" method="post">

    <div>

        <label>GorusmeKonusu</label>

        @Html.TextBoxFor(m => m.GorusmeKonusu, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.GorusmeKonusu, "", new { @style = "color:red" })



        @Html.TextBoxFor(m => m.MusId,

       new {
           @class = "form-control",

           @readonly = "true",
           @Value = @ViewBag.musId

           //htmlAttributes: new 
           //{ 
           //    @Value = @ViewBag.musId
           //    } 
       })




    </div>
    <div style="margin-top:15px">

        <button id="musteriGorusmeEkle" class="btn btn-info">Musteri Gorusme Ekle</button>
    </div>


</form>